### ISSUE TITLE
argument out of range (ArgumentError)

### ISSUE THREAD

**Issue by shivabhusal** [xecutioner/loadshedding-schedule#3]
Hey @xecutioner 

Any idea why I am facing this issue?
```bash
$ schedule -g 2
/home/john/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/time.rb:300:in `local': argument out of range (ArgumentError)
	from /home/john/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/time.rb:300:in `make_time'
	from /home/john/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/time.rb:364:in `parse'
	from /home/john/.rvm/gems/ruby-2.2.1/gems/loadshedding-0.1.7/lib/timer.rb:67:in `change_to_time'
	from /home/john/.rvm/gems/ruby-2.2.1/gems/loadshedding-0.1.7/lib/timer.rb:58:in `time_to_off'
	from /home/john/.rvm/gems/ruby-2.2.1/gems/loadshedding-0.1.7/lib/timer.rb:41:in `find_remaining_time'
	from /home/john/.rvm/gems/ruby-2.2.1/gems/loadshedding-0.1.7/lib/timer.rb:14:in `initialize'
	from /home/john/.rvm/gems/ruby-2.2.1/gems/loadshedding-0.1.7/lib/schedule_formatter.rb:37:in `new'
	from /home/john/.rvm/gems/ruby-2.2.1/gems/loadshedding-0.1.7/lib/schedule_formatter.rb:37:in `set_tim

**Comment by shivabhusal** [comment]
BTW; current date time
```bash
$ date
Sun Mar 20 20:11:49 NPT 2016

**Comment by xecutioner** [comment]
Thanks @shivabhusal : Working on it 
`Finished in 0.002919s, 342.5668 runs/s, 0.0000 assertions/s.

  1) Error:
TimerTest#test_timer:
ArgumentError: argument out of range
    /Users/admin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/time.rb:300:in `local'
    /Users/admin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/time.rb:300:in `make_time'
    /Users/admin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/time.rb:364:in `parse'
    /Users/admin/dev/tools/loadshedding/lib/timer.rb:64:in `change_to_time'
    /Users/admin/dev/tools/loadshedding/lib/timer.rb:55:in `time_to_off'
    /Users/admin/dev/tools/loadshedding/lib/timer.rb:38:in `find_remaining_time'
    /Users/admin/dev/tools/loadshedding/lib/timer.rb:14:in `initialize'
    /Users/admin/dev/tools/loadshedding/test/test_timer.rb:10:in `new'
    /Users/admin/dev/tools/loadshedding/test/test_timer.rb:10:in `test_timer'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/Users/admin/.rvm/gems/ruby-2.2.1/gems/rake-11.1.1/lib" "/Users/admin/.rvm/gems/ruby-2.2.1/gems/rake-11.1.1/lib/rake/rake_test_loader.rb" "test/test*.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)`

**Comment by xecutioner** [comment]
The version has been bumped to 1.8 Please upgrade.
